### ISSUE TITLE
Random screen distortion

### ISSUE THREAD

**Issue by mlabieniec** [jakeday/linux-surface#114]
On Surface book 15" randomly my screen will distort:
![mvimg_20180325_145036](https://user-images.githubusercontent.com/1417045/37880379-4c6c2940-303c-11e8-870b-711c38522efb.jpg)

I don't have anything other than a default installation of the kernel on Ubuntu 17.10, no real pattern or anything, everything works fine and randomly it will just do this and i'll need to reboot. I also tried locking screen rotation didn't seem to change anything. I don't have nvidia drivers installed, just the default setup.

**Comment by jakeday** [comment]
@mlabieniec That distortion comes from the firmware. My workaround has been to disable scaling and use a lower resolution and it's not a problem.

**Comment by mlabieniec** [comment]
Ah gotcha, thanks. Too bad the 4k on here has performed better than anything else ived used so far.

**Comment by remingtonlang** [comment]
Sorry to resurrect a closed issue. I've had some good success so long as I don't plug in an external monitor by setting:
"i915.enable_execlists=0" - in kernel parameters

and

`/etc/modprobe.d/i915.conf
options i915 enable_guc_loading=1 enable_guc_submission=1`


I'm curious your results. It's been incredibly stable for about a week now

**Comment by mlabieniec** [comment]
@remingtonlang has your display been consistently working with this update?

**Comment by remingtonlang** [comment]
@mlabieniec I'm running Ubuntu 17. I had it happening every few hours pretty consistently. Since the change I've gotten it down to about once a week before it craps out on me. Its just me AFAIK testing this so my experience anecdotal. Give it a try and let me know your experience.

I also went poking at the kbl firmware blobs and noticed a few are out of date compared to what is run stock or in Jake's kernel. I tried updating them a few days ago but hit some weird issues where the blobs weren't being be dropped into the image by mkinitramfs. I plan to take another stab at it this weekend.

(This one sounds relevant) https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/i915/kbl_dmc_ver1_04.bin?id=1156e62c5ec45061955a29e1b9299ffda58479d3

https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/i915/kbl_guc_ver9_39.bin?id=de8171590bc29196cb90b7e69b112a8ba26bcaf4
