### ISSUE TITLE
Kernel images starting with version 4.13 fail to load on Surface Book

### ISSUE THREAD

**Issue by ulf-nuernberger** [jakeday/linux-surface#12]
Hi,

while the 4.12 kernel images load correctly on my surface book, the images of the 4.13 series completely fail to load. After grub loads the kernel the display stays black and nothing else happens.
Did you encounter this in your environment too?

BTW: This happens only on the "surface book". The same kernel works like a charm on the Surface Pro 4  Platform.

Model: surface book
System UEFI 90.1427.768
SAM Controller: 90.1610.256
IME: 11.0.15.1003
System Embedded Controller 90.1277.256

Thanks and Regards
Ulf

**Comment by jakeday** [comment]
I never actually finished the 4.13.x series kernels lol! I moved on to 4.14.x series kernel, which I just pushed out now and this is resolved. Enjoy!

**Comment by pierrebeaucamp** [comment]
Just going to drop in here and say that this issue seems to exists on all 4.13 kernels. See https://www.reddit.com/r/SurfaceLinux/comments/77e552/surface_book_will_not_boot_any_version_of_ubuntu/

It has something to do with Intel microcode, which I had to manually load in the bootloader in order for it work. See https://wiki.archlinux.org/index.php/Microcode#Enabling_Intel_Microcode_Updates

But in general, this has nothing to do with this specific Kernel.
