### ISSUE TITLE
All Devices: Bugs on multi monitor

### ISSUE THREAD

**Issue by GammaPi** [jakeday/linux-surface#135]
The position of pen and touch is wrong in the scheme of using multi monitors.
The driver seems to map the cursor to whole screen instead of just that very touch screen.

**Comment by fpoussin** [comment]
Touch + 2nd monitor works fine on SP2017 with ubuntu 18.04

**Comment by jakeday** [comment]
@fpoussin While having a second monitor attached, your touchscreen interacts with the correct touch point? I think that's @GammaPi concern.

**Comment by fpoussin** [comment]
@jakeday yes, everything works as intended.

**Comment by sergiusens** [comment]
I can confirm this

**Comment by GammaPi** [comment]
Well..I'm using display link (a driver for USB monitor ASUS MB16AC), and the mapping isn't correct.
System version: Ubuntu 16.04
Device: Surface book1

I haven't tested on other monitor.
Maybe the monitor is just too special.........

**Comment by jakeday** [comment]
I'm able to duplicate it mapping correctly and incorrectly based on  few variables. I'll look into getting this fixed.

**Comment by jakeday** [comment]
Turns out this is just a configuration issue and nothing wrong with the kernel or drivers. You just need to set the map the output.

xinput map-to-output <device> <output>

You can get your device id by using xinput, and your output device using xrandr. My command looks like this:

xinput map-to-output 14 eDP1
