### ISSUE TITLE
Proper patch files for other distributions

### ISSUE THREAD

**Issue by jrevillard** [jakeday/linux-surface#15]
Dear @jakeday,

Thank you very much for your hard work. I was wondering if it could be possible for you to generate/maintain proper patch files ? It would then be much easier for me to apply them on the official Gentoo kernel images ?

Best,
Jérôme

**Comment by jakeday** [comment]
I would much prefer to maintain the mainline kernel with my changes rather than patch files. Most distros have directions on how to compile their kernel from mainline, though.

**Comment by pierrebeaucamp** [comment]
I respect the decision and I think you should strive for whichever workflow suits you best - but I just want to add that having proper patch files makes this much more portable. I'm also more comfortable to apply patches my self rather than running an "unknown" kernel. 

This shouldn't come off as a request as I'm already in your debt for providing this amazing kernel, I just wanted to add some food for though. I stumbled across this issue while looking for "offical" patch files.

**Comment by pierrebeaucamp** [comment]
I see that you switched to patch files after all. Thank you so much, this greatly facilitates installing the kernel in my distro of choice!
