### ISSUE TITLE
Surface Book 2: Undocking causes `modprobe -r nouveau` to spin.

### ISSUE THREAD

**Issue by qzed** [jakeday/linux-surface#211]
When I undock the clipboard, `/sbin/modprobe -r nouveau` completely claims one core of the CPU. When I try to reattach the clipboard, the base remains unresponsive (no keyboard- or trackpad-input, keyboard backlight for the Fn key works).

I can reproduce this on 4.16, 4.17.1 and 4.17.3.

Current workaround: Run `modprobe -r nouveau` before undocking.

I'll provide some dmesg logs shortly.

**Comment by qzed** [comment]
Oh, and the device is a Surface Book 2 13" with a GTX 1050, to be specific.

Here is the `dmesg` output when undocking without the workaround: [dmesg-undock-spin.log](https://github.com/jakeday/linux-surface/files/2147395/dmesg-undock-spin.log).

And here is the `dmesg` output when removing `nouveau` before undocking: [dmesg-undock-workaround.log](https://github.com/jakeday/linux-surface/files/2147396/dmesg-undock-workaround.log)

What's also interesting is that with the workaround `modprobe nouveau` fails and claims it does not know the chipset (can be reproduced when trying to reload the module manually after the docking). This does not happen when I unload and reload the module without undocking/redocking first.

**Comment by jakeday** [comment]
@qzed It's a timing issue with the udev rule. In most cases, the device will get removed due to bein undocked and the module will get unloaded. However, if the device is fully disconnected and the module unload takes too long, it will hang like you are seeing. This is due to how the nouveau module is handling the removal and resets. We can make a change to that process in the module to correct this. I don't think any other device works quite like the Surface Book 2 so this was never implemented before. I'll add it to the list, shouldn't be too difficult!

**Comment by qzed** [comment]
@jakeday Loosely connected: Do you have any idea if/how it's possible to get some sort of notification/interrupt indicating that a user has requested undocking?

I've been looking at the `MSHW0153` because it seemed like it may provide something like this, but I only get interrupts when the base gets truly disconnected, not already when the user pressed the disconnect button.

**Comment by qzed** [comment]
Can be fixed via https://github.com/qzed/linux-surfacegen5-acpi/issues/7.

**Comment by qzed** [comment]
Basic support for this is now implemented in the [surface-acpi](https://github.com/qzed/linux-surfacegen5-acpi) module, patches and PR will follow soon(ish). Note that this also requires a [user-space daemon](https://github.com/qzed/linux-surfacegen5-dtx-daemon) to work.
