### ISSUE TITLE
Surface Pro 2017: Volume Buttons are Backwards

### ISSUE THREAD

**Issue by Ragora** [jakeday/linux-surface#226]
I was pleased to see that button support was added, though it appears for me (unless I'm just weird) that the volume buttons are inverted. When facing the tablet in the normal orientation with keyboard attached, I would expect the left volume button to decrease volume and the right volume button to increase volume but this behavior is actually inverted for me.

This button behavior would make sense if the tablet were held vertically with the charger facing down (and does indeed work as such). Behavior is still inverted when held the other possible vertical direction (lowest button = volume up, highest button = volume down).

Clean Ubuntu 18.04 install.
Kernel Version 4.17.3-3 having answered "yes" to all prompts on the setup script.

**Comment by qzed** [comment]
Are you positive that this behavior is different than in Windows? I don't have a Surface Pro 2017, but on the Surface Book 2 (same driver) the buttons are also oriented in this, somewhat non-intuitive, way. 

Furthermore, at least on the SB2, there are markings on the buttons themselves indicating that this is in fact the correct behavior. Due to this I'm strongly against modifying the driver to switch the layout depending on the orientation.

If someone knows a way to switch this layout with a user-space script (or something along those lines), that does not also switch the volume buttons on the keyboard, I think we should consider adding that tho this repo as an optional feature.

**Comment by calvous** [comment]
It is as @qzed says. On my Surface Pro 1796 the left side of the butten is marked with '+' and the right has a '-'.

**Comment by Ragora** [comment]
Oops, yeah, my fault. Works the same on Windows though configuration may be nice. I never look at the buttons and just try to set intuitively.

Regardless, not an actual issue then.

**Comment by qzed** [comment]
@Ragora 

> though configuration may be nice

Have a look at https://github.com/qzed/surfacebook2-linux-button-autoremap. It's pretty basic at the moment but feel free to write a PR or issue if you feel that something is missing.
