### ISSUE TITLE
Kernel version

### ISSUE THREAD

**Issue by rogueturnip** [jakeday/linux-surface#233]
Hi there, great project!  I have it working perfectly on an old Surface Pro.

What I was wondering, is there a list anywhere that shows what what features have been merged back into the mainline kernel so it's easy to determine what will work when things like Ubuntu 18.04 are installed.

Thanks!

**Comment by jeffinman** [comment]
Great question. Just to add to that, I couldn't find in the README whether auto-updates may cause an issue, particular upgrades. I have Ubuntu running lovely on my Surface Book 2 since I installed this morning with your patch - thanks so much!

But a few (far more experienced in linux) friends were interested to know whether there would be issues with upgrades.

**Comment by jakeday** [comment]
I will look into it!
