### ISSUE TITLE
Surface Go - Touchscreen

### ISSUE THREAD

**Issue by a0910115172** [jakeday/linux-surface#251]
I am the Surface Go user. I have a touchscreen problem: If I want to slide, it will click first time and go slide. How can I modify this? Thank you.

**Comment by a0910115172** [comment]
Solve the touch screen suspend bug by me.
add this in boot script(init.sh):

echo "on" > /sys/devices/pci0000:00/0000:00:15.1/i2c_designware.1/power/control

It can always turn on touchscreen and never suspend in 1000ms and we can get smoothly to use touchscreen.

**Comment by jakeday** [comment]
This has been fixed in the latest releases. Please make sure you run setup.sh script again.

**Comment by choeffer** [comment]
See https://www.reddit.com/r/SurfaceLinux/comments/ah30w8/surface_go_remove_not_existing_battery_from_gnome/ I added some more infos

**Comment by thebitstick** [comment]
Not sure if I should make a new issue about this but the fix for **switching the touchscreen from auto to on** for the Surface Go doesn't work on Fedora.
While Ubuntu and Arch are the only officially supported distros for this project, I'd imagine it doesn't work on Arch either, so it may be worth to have a look.

Installing the surfacego-touchscreen script (which is done automatically using setup.sh) uses update-rc.d which doesn't exist on Fedora (and Arch), and in order to use the script with Systemd (which is technically done anyways on Ubuntu), you need to include metadata for Chkconfig in the script, (as well as add #!/bin/bash at the top, like any shell script) which handles legacy init.d scripts on Fedora/RHEL.
I could make a PR for this, as well as making the script a bit more accessible to users of non-Ubuntu distros.
