### ISSUE TITLE
Nvida card not detected

### ISSUE THREAD

**Issue by A-I-Ivanov** [jakeday/linux-surface#253]
Let me know what I can do to help diagnose this. I've tried a million things, and I just  cant get the dedicated card to show up. I followed your instructions and installed the NVIDA 390 drivers.

**Comment by dDoom** [comment]
I have same problem. Surface book 2 not detect NVIDIA card.

**Comment by remingtonlang** [comment]
I'm on a SB2 as well and can get the nvidia card detected and working though suffers from thermal throttling, documented here: https://wiki.archlinux.org/index.php/Microsoft_Surface_Book_2#Nvidia (Jake's aware of the issue)

If you guys cant get it detected at least it sounds like maybe just a installation/configuration issue. Detection of the actual card however is possible with the driver. I just retried it a few ago with no issues detecting hoping 4.18 fixed the thermal issue.
 1. Install the nvidia 396 driver (dkms version is the one I could get to work)
   - Watch out very carefully during installation. At least in Ubuntu apt will not catch failed compilation errors of the module and report it installed even if missing(in my case I was missing libelf-dev if memory serves me)
 2. Obviously use Xorg not Wayland
 3. Remove /etc/X11/xorg.conf.d/20-intel.conf, which is installed via Jakes setup script and interferes with the automatic configurations in /usr/share/X11/xorg.conf.d directory

**Comment by RodriguezLucha** [comment]
> Edit: Just to point out, you'll cook your laptop if you get it working until the thermal issues are addressed. The dGPU doesn't work ATM, but not because of detection

Thanks for that little note!

**Comment by A-I-Ivanov** [comment]
Thanks for the updates guys. I think I'll wait until the thermal issue is solved. The surface book doesn't do well with heat. to begin with.

**Comment by sebastiani** [comment]
I'll wait until this thermal issue is resolved as well. Looking forward to it!

**Comment by jakeday** [comment]
Just remove my xorg script and it'll work. There are still issues that need to be resolved on other issue tickets first, though.

**Comment by dotvezz** [comment]
Just to clarify the thermal issue: The fan itself *does* spin up without any problems when it's needed. My guess is it's controlled directly by firmware (rather than software drivers) in a way that's unique to the SB2 family.

So it won't cook, the fan will spin up whenever it's needed (I know this because of the times I've forgotten to power off and put the SB2 in my bag). There is also a good reason to install the driver right now: By installing `nvidia-dkms` and installing+enabling `bumblebeed`, Bumblebee will automatically turn the card off.

By default, the 1060/1050 is turned on and using some small amount of battery power, the driver is needed to turn it off.
