### ISSUE TITLE
Surface Pro 2017 Wifi freeze and needs reboot 4.18.11

### ISSUE THREAD

**Issue by pijulius** [jakeday/linux-surface#298]
Hi Jakeday,

Hope you won't mind me creating a new issue regarding this, just would like to also let you know personally in case it would be something you could address, I have found a bugreport on ubuntu too re this here:
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1730924

and attaching the two dump files they requested too maybe it helps also can duplicate it pretty easily so if help is needed re testing I'm here.

As I offered a reward ($100) there too would like to also offer that here too if you wont' mind, I know its not that much but as gesture of appreciation hopefully you will receive it with kindness and surface pro 2017 will fully work once you finish you work on it :)

Thanks again for all your hard work!
Regards,
Julius

[coredump.txt](https://github.com/jakeday/linux-surface/files/2578054/coredump.txt)
[lspci.txt](https://github.com/jakeday/linux-surface/files/2578055/lspci.txt)

**Comment by jonas2515** [comment]
So I just found a thread about a similar issue by some people in the TI dev community, and thankfully they decided to share their findings: 

https://e2e.ti.com/support/legacy_forums/embedded/linux/f/354/t/564867
https://e2e.ti.com/support/processors/f/791/p/577631/2129397#2129397

Even though this has nothing to do with our platform, they were encountering the same timeouts where the driver waits for data from the card but doesn't receive anything and they concluded that it's a bug in the PCI interrupt handling of their platform.

As suggested by Michael Heinemann in the thread disabling message-signaled interrupts in the pci driver with the kernel parameter `pci=nomsi` makes the wifi more stable. This seems to be an effective workaround for our issue because the driver no longer resets the card after the timeouts happen (resetting or dumping seems to crash the firmware), but just ignores the timeout instead. It obviously isn't a real fix, the card is still unresponsive every few minutes while those timeouts happen, but at least it doesn't crash anymore and is usable.

I guess it would also be possible to patch the mwifiex driver so it doesn't try to reset the card and dump the firmware after command timeouts.

Now we get those error messages instead of the timeout messages:
```
[  333.494402] mwifiex_pcie 0000:01:00.0: cmd_wait_q terminated: -110
[  333.494405] mwifiex_pcie 0000:01:00.0: failed to get signal information
```

@qzed Any idea if there might be an issue with the PCI interrupt handling, could this also be the reason why we have to use `tsched=0` in pulseaudio to fix audio glitches?

**Comment by qzed** [comment]
@jonas2515 To be honest, I have no idea. I haven't looked into the audio issue at all and only glanced a bit at the wifi issue. Also I've only ever had problems with the wifi crashing when I experimented with power management (tlp) or suspend/hibernate (although that doesn't necessarily mean the wifi controller isn't handling power-management well, I guess this could also be some PCI controller behaving weird, e.g. in reference to interrupts, when power-managed). I can't really help you much at the moment without looking further into this, sorry.

**Comment by pijulius** [comment]
Hi Jonas, 

Thanks for the help, tried both methods, first added "pci=nomsi" right before the quiet kernel parameter but no help, and then modified the mwifiex driver and returned void on the timeout cmd function and then indeed it doesen't die out just get the cmd_wait_q terminated -110 errors going on as you said.

The problem unfortunately still is that internet still stops to work but at least because there isn't any core dumps the driver still works and can be removed which means the pc will reboot without needing to hold down the power button so it's easier to restart :)

I will try to play around with that function now maybe will be lucky, in any case thanks again for the pointers, will keep you guys updated and please don't hesitate to write if anything else pops up in your minds as ready to test all that's possible.

Regards,
Julius

**Comment by jonas2515** [comment]
@pijulius Are you sure the workaround doesn't work? When the timeout appears it doesn't work for a few seconds, but after that it's running just fine again.

I also have my bluetooth turned off by the way since that fixes suspend (the bluetooth usb device sends a wakeup event on suspend), so that might help, too.

**Comment by pijulius** [comment]
@jonas2515 Yep, just had it happening again, attached you can see the dmesg output.

FYI: Using 
Latest qzed/linux-surface
Latest qzed/linux-surfacegen5-acpi-notify
Kernel-4.18.11
Fedora 29

cat /etc/default/grub 
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
GRUB_DEFAULT=saved
GRUB_DISABLE_SUBMENU=true
GRUB_TERMINAL_OUTPUT="console"
GRUB_CMDLINE_LINUX="resume=/dev/mapper/fedora-swap rd.lvm.lv=fedora/root rd.lvm.lv=fedora/swap rhgb pci=nomsi memmap=630M\\\$810M quiet"
GRUB_DISABLE_RECOVERY="true"

Modified kernel/drivers/net/wireless/marvell/mwifiex/cmdevt.c
void mwifiex_cmd_timeout_func(...) { return; }

as for some reason "pci=nomsi" doesn't do anything for me.
Bluetooth is also turned off and never use it, keyboard is also not attached.

Also if I manually do "modprobe -r mwifiex_pcie" after some time it removes and then can suspend and after wakup wifi works again.

Please let me know if I missed something or are doing wrong.

**Comment by prog-amateur** [comment]
Hi, thanks for your help ! Since January, did you encounter wifi issues ? 

On my side, I have used your script (I don't have jakeday's kernel installed), and when I do `lspci -s 01:00.0 -vvv` I don't have any output as `ASPM Disabled`. What do you think ? 
Please find my output here : 
```
01:00.0 Ethernet controller: Marvell Technology Group Ltd. 88W8897 [AVASTAR] 802.11ac Wireless
	Subsystem: SafeNet (wrong ID) 88W8897 [AVASTAR] 802.11ac Wireless
	Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 0, Cache Line Size: 64 bytes
	Interrupt: pin A routed to IRQ 47
	Region 0: Memory at c0500000 (64-bit, prefetchable) [size=1M]
	Region 2: Memory at c0400000 (64-bit, prefetchable) [size=1M]
	Capabilities: <access denied>
	Kernel driver in use: mwifiex_pcie
	Kernel modules: mwifiex_pcie
```
Thank you !
