### ISSUE TITLE
VirtualBox misses header files

### ISSUE THREAD

**Issue by hobbeshunter** [jakeday/linux-surface#33]
First of all thank you for all your work. This is definitely the best kernel I had be running on my Surface Pro 4 for now.

There is only one issue: I can't run VirtualBox on it. I'm using Ubuntu 17.10 and VirtualBox straight from the [oracle ppa](https://www.virtualbox.org/wiki/Linux_Downloads). After I installed your kernel I tried to run `sudo dpkg-reconfigure virtualbox-5.2` which reported:
```
This system is currently not set up to build kernel modules.
Please install the Linux kernel "header" files matching the current kernel
for adding new hardware support to the system.
```

But according to ``sudo apt-get install linux-headers-`uname -r` `` linux-headers-4.14.0-jakeday-surface is installed.

Do you have any hint for me to solve that issue?

Cheers,
Martin

**Comment by jakeday** [comment]
This is an issue with VirtualBox. They will be updating to support 4.14 kernels shortly I imagine. It usually takes them a bit for newer kernels. You can see the ticket here:

https://www.virtualbox.org/ticket/17267

**Comment by hobbeshunter** [comment]
Thanks a lot and sorry for bothering you.

**Comment by jakeday** [comment]
@hobbeshunter No worries! I'm happy to help!

**Comment by abutre** [comment]
Hello. The issue with Virtual Box seems to be solved, but reconfigure still fails while running check_module_dependencies.sh (debug output attached).
It seems caused by some links setup on kernel installation on /lib/modules/4.14.2-jakeday-surface :

build -> /home/jake/ipts/build/kernel
source -> /home/jake/ipts/build/kernel
[check_module_dependencies.log](https://github.com/jakeday/linux-surface/files/1516168/check_module_dependencies.log)
