### ISSUE TITLE
Cant start docker daemon due to iptables

### ISSUE THREAD

**Issue by scotty-c** [jakeday/linux-surface#330]
I am running Debian 9 on a surface book 2 with the 4.18.20-surface-linux-surface kernel and cant start the Docker daemon due to failing with the following error 
```Jan 01 21:55:26 surfacebook dockerd[3700]: Error starting daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT c
Jan 01 21:55:26 surfacebook dockerd[3700]: Perhaps iptables or your kernel needs to be upgraded.
Jan 01 21:55:26 surfacebook dockerd[3700]:  (exit status 3)
```
I have tested with the backports 4.18 kernel and that does not have the issue with the daemon starting, but a whole heap of other stuff doesnt work.

Any help would be appriciated and thanks for all the hard work you put into this project.

**Comment by sphh** [comment]
Is this connected to #328?

**Comment by qzed** [comment]
@sphh seeing as UFW is a frontend for iptables, probably in some way.

**Comment by samvtran** [comment]
A couple observations from my Arch install:

I get the following error when I try to start docker with the new 4.18.20-surface-linux-surface kernel:
```
dockerd[1112]: Error starting daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables --wait -t nat -N DOCKER: iptables v1.8.2 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
```
Based on that I'd suspect the issue is the [`CONFIG_IP_NF_NAT`](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/net/ipv4/netfilter/Kconfig?h=v4.18.20#n282) option (responsible for the `iptable_nat` module) that's missing from the new [config file](https://github.com/jakeday/linux-surface/blob/9b218f92455842e5185812e213044c5770bdda47/configs/4.18/config).

In the meantime [`v4.18.20-pre2`](https://github.com/qzed/linux-surface/releases/tag/v4.18.20-pre2) is working fine here.

**Comment by qzed** [comment]
I guess that would explain it! Thanks! It seems like there are also other options in the config (`CONFIG_NF_CONNTRACK_IPV4`, `CONFIG_NF_TABLES_IPV4`, `CONFIG_NF_TABLES_ARP`) that should be enabled?

**Comment by samvtran** [comment]
Looks like Jake is recompiling now, so hopefully that adds all the necessary flags :crossed_fingers:, but I ran the Docker [kernel compat script](https://github.com/moby/moby/blob/master/contrib/check-config.sh) and it's flagging three "generally necessary" options that are missing:
- `CONFIG_IP_NF_NAT`
- `CONFIG_NF_NAT_IPV4`
- `CONFIG_IP_NF_TARGET_MASQUERADE`

**Comment by samvtran** [comment]
Looking good here with [4.18.20-2](https://github.com/jakeday/linux-surface/releases/tag/4.18.20-2) :sunglasses:

**Comment by scotty-c** [comment]
Thanks for pushing the changes so quickly.
