### ISSUE TITLE
Installation on Manjaro

### ISSUE THREAD

**Issue by JamesBr0wn** [jakeday/linux-surface#331]
Hello @jakeday
Thank you for your work!
I wonder how to install this kernel on manjaro / surface pro 2017. I tried the steps in "Compiling the Kernel from Source", but could not see any built kernels after it says "All done! Please reboot.", and reboot also didn't help.. Besides,  after the installation, the system would shut down automatically when it's supposed to suspend.

**Comment by qzed** [comment]
The README (specifically `make deb-pkg`) is for Debian-based systems, so strictly following this will give you `.deb` packages. If you want a kernel package for your distribution, I'd recommend you have a look at [this](https://wiki.archlinux.org/index.php/Kernel/Arch_Build_System) (I assume this is also relevant for Manjaro).

With regards to the shutdown instead of suspend: If you've selected the corresponding option in `setup.sh`, suspend will be replaced with hibernate. This could then either look like it's shutting down, or really shut down (issue #266).

**Comment by JamesBr0wn** [comment]
@qzed Thanks a lot. I will try that later.
By the way, are your "linux-surfacegen5-acpi" patches contained in this repository, or I have to patch them myself.

**Comment by qzed** [comment]
As of the 4.18.20 release, they are fully integrated, so you only need to apply the patches of this repo!

**Comment by JamesBr0wn** [comment]
Thanks.

**Comment by qzed** [comment]
Glad to be able to help! Also there are some existing PKGBUILDs for Arch, e.g. [this one](https://github.com/martinnyborg/arch-surface-jakeday-kernel), that altough it's a bit outdated might help you.

**Comment by JamesBr0wn** [comment]
Found a good  repo for arch based systems, maybe adding a link of it to the readme file could be helpful for arch users. https://github.com/dmhacker/arch-linux-surface. @qzed

**Comment by qzed** [comment]
@JamesBr0wn Thanks for the link! Looks great!
