### ISSUE TITLE
apparmor-fix-4.14.patch has an outdated context

### ISSUE THREAD

**Issue by thekswenson** [jakeday/linux-surface#36]
The final part of the papparmor-fix-4.14.patch patch is:

```
diff --git a/apparmor.d/usr.sbin.cupsd b/apparmor.d/usr.sbin.cupsd
index e0c7e40..469e24f 100644
--- a/apparmor.d/usr.sbin.cupsd
+++ b/apparmor.d/usr.sbin.cupsd
@@ -42,6 +42,8 @@
   network econet dgram,
   network ash dgram,
 
+  network unix stream,
+
   /bin/bash ixr,
   /bin/dash ixr,
   /bin/hostname ixr,
```

But the context is wrong, as my file has the following lines as context:

```
  /{usr/,}bin/dash ixr,
  /{usr/,}bin/bash ixr,
  /{usr/,}bin/cp ixr,
```

**Comment by jakeday** [comment]
@thekswenson Each distro handles apparmor contexts a little differently and it would be very difficult to maintain patches for each. You'll have to manually add the lines if the patch doesn't apply cleanly. To be more compatible, I'll take out the cupsd lines and just have the fix for dhclient in there.

**Comment by thekswenson** [comment]
No problem.  I'm guessing the change came with 17.10.

**Comment by jakeday** [comment]
Very likely. I just pushed an update to remove patching cupsd.
