### ISSUE TITLE
Can you publish a complete surface installation package directly?

### ISSUE THREAD

**Issue by RoyCao1995** [jakeday/linux-surface#394]
My device is new surface pro. I'm a novice and I can't operate by readme.
thank you！

**Comment by versipellis** [comment]
I'm confused.. how much more complete of a package than running a single setup.sh file can you get?

**Comment by jakeday** [comment]
@RoyCao1995 I don't understand either. You just need to run the setup.sh script. I won't be making a package that can be installed for all the configs as it varies from system to system.

**Comment by Thebigbignooby** [comment]
from the README

> Downloads for ubuntu based distros (other distros will need to compile from source using the included patches):
https://github.com/jakeday/linux-surface/releases
You will need to download the image, headers and libc-dev deb files for the version you want to install.

leads me to believe I need to do this before the linux install,
however you go on to give linux commands to run, which suggests we should do the install first ?

THe thing is my keyboard won't work so I can't even go through with the install and I suppose I need your special surface fix to make the keyboard work in the first place. Its really not clear what the different steps are...

**Comment by versipellis** [comment]
@Thebigbignooby That is a self-contained section - what it means is that if you have a Ubuntu-based distro, just run `setup.sh` and it'll download the image and headers for you; if you don't have a Ubuntu-based distro, you'll need to compile from source.

It's probably a little less clear since that might be a leftover bit of documentation from the old process where you used to need to manually download the image and headers to install.
