### ISSUE TITLE
Hibernate on Linux Surface Book 2 doesn't actually hibernate

### ISSUE THREAD

**Issue by ezyang** [jakeday/linux-surface#424]
On a new Ubuntu install:

```
ezyang@naginata:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

I've installed the latest kernel (as of, yesterday, I think?)

```
Linux naginata 4.19.27-surface-linux-surface #2 SMP Thu Mar 7 13:20:42 EST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

I have overwritten suspend with hibernate:

```
ezyang@naginata:~$ ls -l /etc/systemd/system/suspend.target
lrwxrwxrwx 1 root root 36 Mar  7 23:34 /etc/systemd/system/suspend.target -> /lib/systemd/system/hibernate.target
```

However, when I actually try to suspend, it seems to just power off, and when I boot up again I don't get any of my state back.

Let me know if there's any other information, or older kernels, I can try.

**Comment by TimmyOl** [comment]
Im no linux expert but i got it to atleast save the state even though it seems to power off instead of hibernate, The swap seems to have been the problem for me, i followed this guide to make a swap disk instead of a file:

https://ubuntuforums.org/showthread.php?t=2334278 

like i said im a novice when it comes to linux but that atleast worked for me.

**Comment by ezyang** [comment]
Oh you're right, I don't actually have a swap partition. Guess I better fix that first :)
