### ISSUE TITLE
sudo pm-hibernate freezes the screen instead of "hibernating"

### ISSUE THREAD

**Issue by sokolowistan96** [jakeday/linux-surface#433]
Everything else works fine, other than that. It seems to me, that suspend wasn't properly replaced by the script (that installs the kernel), because using suspend (by binding the power-button to it for example) results in a different problem, where the screen gets dark, than maybe shows up again for a short time and then goes dark again without really turning off. sometimes (in the case of suspend) it also just turns itself off and than on again, while forcing me to boot into windows (arrows not working in grub)

I'm using the latest kernel on my surface book 2 (13'')

**Comment by ezyang** [comment]
I don't know why `pm-hibernate` is broken, but don't use it; instead, do `systemctl hibernate`. The former doesn't work for me; the latter does.

**Comment by sokolowistan96** [comment]
Thanks mate, that seems to be working, however it takes some time until it is fully shutdown, so that for the next 30-60 secs I'm not able to turn my device on again. Thats not really a problem, since I won't hibernate if I am planning to use it in the next 30-60 secs haha

However, there is another issue: After starting from hibernation, touch, wlan and even mouse-scrolling aren't working. Perhaps you've had the same issue and were able to resolve it?

**Comment by ezyang** [comment]
Check https://github.com/jakeday/linux-surface/issues/431 for wifi.

Also, apparently suspend is working, so give that a try too.

**Comment by tmarkov** [comment]
What you describe suggest the pre/post sleep script isn't working. So you have the file /lib/systemd/sysyem-sleep/sleep and is it executable?

**Comment by NitroBAY** [comment]
What if I don't have systemd but I choosed openrc (I'm using gentoo) is systemd a requirement ?

**Comment by NitroBAY** [comment]
@jakeday @tmarkov  do you know know about openrc's compatibility ? Do I need to switch ?

**Comment by tmarkov** [comment]
@NitroBAY I don't see why openrc would work. You need to set it up as follows:
1. Use "freeze" state to suspend instead of "mem".
2. Unload the following modules before suspend and hibernate: intel_ipts, mei_me, mei, mwifiex_pcie, mwifiex, cfg80211 (in this order to account for dependencies); and reload them (in reverse order) after you wake the surface up.

**Comment by NitroBAY** [comment]
When I echo freeze > /sys/power/state the system literally freezes. Like the screen doesn't turn off it just freezes and then I can do anything (using keyboard, touchpad) but my computer won't respond. Is it the expected behavior if I don't unload/reload modules ?

**Comment by tmarkov** [comment]
@NitroBAY In my case when I don't unload the modules before echo freeze > /sys/powe/state, it does suspend, but hangs afterwards on wakeup. If I do unlaod the modules, echo freeze works as it should. So it's a bit different for me, but I'd not be surprised if your issue is also because of not unloading the modules first.

**Comment by Minteck** [comment]
I have the same issue with both `pm-hibernate` and `systemctl hibernate` (screen is black and computer don't shutdown).

Here's my config:
- Kubuntu 18.04.2
- Swap 3,8 GiB
- RAM 3,3 GiB
- AMD A9/Radeon R5 APU
- 1366x768 60 FPS _(exactly it's 59,97 FPS)_ Internal Laptop Screen (eDP)
- Kernel version 4.18.0-25-generic (from `uname -r`)
- Seagate SATA HDD
- Realtek Bluetooth/Audio/WLAN
- Lenovo Ideapad 320-15AST Laptop
- Linux Partition : /dev/sda6, Swap Parititon : /dev/sda7

Can you help me? Because I need hibernation when I need to resume my work later and faster.
Thanks.
