### ISSUE TITLE
Surface Pro 4: Type cover won't properly reattach when removed

### ISSUE THREAD

**Issue by Earth-2** [jakeday/linux-surface#54]
When I remove my type cover, it won't work after it's reattached.  The keyboard and mouse are both unresponsive and the lights don't illuminate either.  I've included the dmesg log below--I assume most of the relevant stuff is at the bottom but let me know if you need more info.

[typecover001.txt](https://github.com/jakeday/linux-surface/files/1532390/typecover001.txt)

**Comment by tcinbis** [comment]
@Earth-2 I have can reproduce the same behaviour on my SP4

**Comment by jakeday** [comment]
@Earth-2 According to your dmesg log, it looks like it's picking it up again and connecting just fine. What distro are you using? Can you try the latest 4.14.5 kernel? There's changes to hid support since this issue was opened.

**Comment by Earth-2** [comment]
I'm using Arch, currently with the [linux-surface4 kernel in the AUR](https://aur.archlinux.org/packages/linux-surface4/).  I'll try building linux-surface with the 4.14.5 kernel and see what happens.

**Comment by tcinbis** [comment]
@Earth-2 I would like to do the same, but unfortunately I am not quite sure how to do it. Would you minde to briefly describe how you compiled the kernel for arch?

**Comment by jakeday** [comment]
@Earth-2 @tcinbis I'm at a loss here. According to the logs provided, the kernel is picking it back up fine and I don't see any issues. I'm also not able to duplicate this in Ubuntu with my kernel debs. Are you sure you have everything setup correctly per the instructions in my repo?

**Comment by tcinbis** [comment]
@jakeday I definitely followed your instructions, but have a little bit older kernel version. It is 4.14.2 because their is no newer aur package available and I am not sure how to compile my own kernel.

**Comment by jimdigriz** [comment]
A udev kludge for this is:
```
# handle typing cover disconnects
# https://www.reddit.com/r/SurfaceLinux/comments/6axyer/working_sp4_typecover_plug_and_play/
ACTION=="add", SUBSYSTEM=="usb", ATTR{product}=="Surface Type Cover", RUN+="/sbin/modprobe -r i2c_hid && /sbin/modprobe i2c_hid"
```

**Comment by jakeday** [comment]
@jimdigriz That will definitely address the issue. It will force the subsystem to re-attach the system device. I'll make note of it in the readme.

**Comment by tcinbis** [comment]
@jimdigriz Thank you very much, it works!

@jakeday Maybe also add this script [here](https://gist.github.com/anonymous/c6012cfed0936bf40006f0b980afc691) 
For me to run this script on arch, I had to replace line 8 with the following line:
`log.addHandler(journal.JournalHandler())`

**Comment by tcinbis** [comment]
@jimdigriz what about the little python script? The sensors seem to work afterwards

**Comment by jimdigriz** [comment]
No idea what python script you are referrering to, sorry.  I don't use jakeday's tree directly, I just cherry pick the bits I need for my own surface project.  Cheers

**Comment by tcinbis** [comment]
@jimdigriz I am talking about the script I mentioned in my previous comment ([here](https://gist.github.com/tcinbis/7ee22a3aa2da3693ffb16fc9217f1045)), which you can find if you read the original post on reddit.

Instead of `RUN+="/sbin/modprobe -r i2c_hid && /sbin/modprobe i2c_hid"` you write `RUN+="/path/to/script"`. Worked for me multiple times without any sensors becoming unavailable.

**Comment by jimdigriz** [comment]
The problem I am describing has nothing to do with how you read the sensors, the problem is that (for whatever reason) on my laptop, calling `/sbin/modprobe -r i2c_hid && /sbin/modprobe i2c_hid` under `udev` (even when I try wrapping it in a `/bin/sh -c "..."`) seems to not do the actual load of the module after an unload.

I never found the time to look into it, and I only use the sensor anyway occasionally for setting the [brightness of my backlight](https://github.com/jimdigriz/debian-mssp4#multimedia-keys) so not overly bothered if it does not work.

**Comment by PaulBatchelor** [comment]
> A udev kludge for this is:
> 
> ```
> # handle typing cover disconnects
> # https://www.reddit.com/r/SurfaceLinux/comments/6axyer/working_sp4_typecover_plug_and_play/
> ACTION=="add", SUBSYSTEM=="usb", ATTR{product}=="Surface Type Cover", RUN+="/sbin/modprobe -r i2c_hid && /sbin/modprobe i2c_hid"
> ```

This config was incorrectly copied from the original reddit thread (@jimdigriz kudos for linking to the source). `ATTR` should be `ATTRS`. 

This will work:

> ACTION=="add", SUBSYSTEM=="usb", ATTRS{product}=="Surface Type Cover", RUN+="/sbin/modprobe -r i2c_hid ; /sbin/modprobe i2c_hid"
