### ISSUE TITLE
Watching YouTube causing overheating

### ISSUE THREAD

**Issue by shadowrylander** [jakeday/linux-surface#555]
Hello! <br>
&nbsp;&nbsp;&nbsp;&nbsp; The tablet portion of my `SB2 17"` seems to be dangerously overheating whenever I'm watching youtube videos (not the base where the dedicated graphics card is); as this doesn't happen on my Windows 10 install, could it possibly have anything to do with the kernel? I'm afraid for both the SSD in the tablet, as well as the stickers on the back, to a lesser extent :joy_cat:. <br>
Thank you kindly for your help on the matter!

**Comment by qzed** [comment]
This is most likely due to missing hardware acceleration for video decoding and doesn't have to do anything with the kernel itself. Unfortunately that's a well known issue on Linux for both Firefox and Chrome/Chromium. There are some settings in the browser that you can tweak that might fix this, but HW acceleration still has room to improve.

**Comment by shadowrylander** [comment]
Ah, yes; that makes sense. Where can I get the settings I might need to change to attempt to fix this?

**Comment by shadowrylander** [comment]
Never mind; I forced hardware acceleration usage in Chrome. However, I'll leave this open for now in case there's any more discussion on the matter.

**Comment by shadowrylander** [comment]
Actually, no; it only overheats for certain videos. Still didn't happen on Windows, though.

**Comment by korakios** [comment]
Only Chromium beta supports hardware acceleration .
There are some workarounds with browser extensions that open YouTube links in VLC/SMPlayer.
Copying pasting a link to VLC or SMPlayer can also play the video in 720p 

Maybe you can close this issue ?

**Comment by qzed** [comment]
@shadowrylander Hardware-acceleration depends on many factors, including GPU (in our case Intel's iGPU), the browser and its settings (as @korakios pointed out), and also the type of codec used for the video (thus some might work and some don't). You might want to have a look at VA-API (https://01.org/vaapi), that's the API provided by Intel to support HW acceleration. Again, the browser has to support this (and if necessary it has to be enabled there).

It's not an issue that we will deal with in this repo, as it is much too complex for that and the issue affects all Intel CPUs, and pretty much all Linux devices. HW acceleration has historically been worse on Linux than on Windows (AFAIK mostly due to browser support, which might be a result of the more segregated driver landscape for this). It certainly is not a Surface specific issue, so I'm going to close this.

**Comment by shadowrylander** [comment]
@korakios @qzed Fair enough! Thanks for the in any case!
