### ISSUE TITLE
SB1 or SB2 for better support?

### ISSUE THREAD

**Issue by deb75** [jakeday/linux-surface#91]
Hello,

Is it easy to install linux (say ubuntu) on a surface book ?

Which surface book (1 or 2) is the most usable with linux currently ?

I heard that the dGPU on the SB2 is drastically throttled down as soon as it gets hot,
which means it loses most of its power ? Can you still benefit from all the nvivdia gpu
power with linux ?

Will the suspend to ram be supported one day ? Or is it just hopeless ?

Regards

**Comment by jakeday** [comment]
@deb75 They are both mostly stable. With the SB1, everything works except the dGPU, cameras and connected-standy. With the SB2, everything works except the battery readings, volume buttons, cameras and connected-standy. You can use hibernate instead of connected-standy on both. Both have been daily drivers and I'm close to having everything working except connected-standy, so go with whichever you prefer.

**Comment by thekswenson** [comment]
Is there no problem with hibernate on those devices? 

The surface pro 4 is unstable and hibernate either doesn't work, or when it does the wifi gets into an unrecoverable state.

I unfortunately have not been able to use my SP4 machine as my work machine because it's not dependable.  It's impractical to have a portable computer that cannot save its state in low power.

**Comment by deb75** [comment]
Hello,

@jakeday 

Thanks first for reformulating my question.

About the SB2 dGPU I would like to be sure, some people reports the dGPU  is throttled down as soon as you put a load on it, because of a bad fan reading, which drastically lowers its performance.

Is it true ? or can you make full use of the dGPU ?

Also, is there still one iGPU ? is there some kind of optimus technology ? If so, can you switch easily between both ?

Thanks in advance for your attention

Regards

**Comment by jakeday** [comment]
@thekswenson I've been testing on a SB1 and SB2 and do not have hibernate issues with either.

**Comment by jakeday** [comment]
@deb75 Yes that is true, but it should be addressed soon.

**Comment by deb75** [comment]
@jakeday 

I read elsewhere (reddit) that SB2 with dGPU can still make use of the iGPU (UHD 620) and that you can switch between both with bumblebee, more preciisely one can switch to the dGPU with bumblebee. If this is functional, I think I would go for the SB2, because I only need the dGPU for some games.

How about the battery life with linux ? With windows, it seems to reach 10 hours, does it hold with linux ?

Also, as the suspend to ram does not work, I wonder how fast is the suspend to disk. I guess it should be really fast with SSD (?)
